#!/usr/bin/env bash

# Canonical host-native network defaults. Keep these conservative: callers that
# intentionally enable TUN or DNS must opt in explicitly.
mihomo_resolve_deploy_settings() {
  MIHOMO_TUN_ENABLE="${MIHOMO_TUN_ENABLE:-0}"
  MIHOMO_DNS_ENABLE="${MIHOMO_DNS_ENABLE:-0}"
  MIHOMO_RESOLVED_VIA_MIHOMO="${MIHOMO_RESOLVED_VIA_MIHOMO:-$MIHOMO_DNS_ENABLE}"

  local name value
  for name in MIHOMO_TUN_ENABLE MIHOMO_DNS_ENABLE MIHOMO_RESOLVED_VIA_MIHOMO; do
    value="${!name}"
    if [[ "$value" != "0" && "$value" != "1" ]]; then
      printf 'ERROR: %s must be 0 or 1, got %q\n' "$name" "$value" >&2
      return 1
    fi
  done
}

# This is intentionally reset on source: an inherited environment value is
# never treated as ownership of a file that the helper may delete.  Keep a
# separate bit for the pre-source state so an operator cannot smuggle a path
# through MIHOMO_OWNED_KNOWN_HOSTS_FILE and make the cleanup trap unlink it.
MIHOMO_EXTERNAL_KNOWN_HOSTS_CONFIG=0
if [[ -n "${MIHOMO_OWNED_KNOWN_HOSTS_FILE:-}" ||
      -n "${MIHOMO_GENERATED_KNOWN_HOSTS_FILE:-}" ||
      -n "${MIHOMO_KNOWN_HOSTS_FILE:-}" ]]; then
  MIHOMO_EXTERNAL_KNOWN_HOSTS_CONFIG=1
fi
MIHOMO_GENERATED_KNOWN_HOSTS_FILE=""
MIHOMO_GENERATED_KNOWN_HOSTS_IDENTITY=""
MIHOMO_OWNED_KNOWN_HOSTS_FILE=""
MIHOMO_KNOWN_HOSTS_FILE=""

# Any host-native mutation must be an explicit, identity-bound operation.  The
# caller supplies the parsed --confirm state; this helper refuses an unpinned
# host and verifies the advertised SSH host key before the first write.  The
# host list is intentionally checked in: an environment value can narrow the
# target to one of these names, but can never add a new destination.
MIHOMO_CHECKED_IN_HOSTS=(
  rainierdev.heiyu.space
  rainierspace.heiyu.space
  rainierserver.heiyu.space
)

# These are reviewed host identities, not values supplied by the invoking
# shell.  An environment setting may narrow a target, but cannot replace the
# key that is accepted for it.
declare -A MIHOMO_CHECKED_IN_FINGERPRINTS=(
  [rainierdev.heiyu.space]='SHA256:Vk9aKER8IP4mmF9gYII3t32OTjaDh6fbOxGRebperKw'
  [rainierspace.heiyu.space]='SHA256:ixyHYt/afV2BxcOqlJKyrubLTQwhjwSV2d3F4GTISxs'
  [rainierserver.heiyu.space]='SHA256:Vk9aKER8IP4mmF9gYII3t32OTjaDh6fbOxGRebperKw'
)

mihomo_checked_in_fingerprint() {
  local host="$1"
  [[ -n "${MIHOMO_CHECKED_IN_FINGERPRINTS[$host]:-}" ]] || return 2
  printf '%s\n' "${MIHOMO_CHECKED_IN_FINGERPRINTS[$host]}"
}

mihomo_file_identity() {
  local path="$1"
  local identity
  if identity="$(stat -c '%d:%i' -- "$path" 2>/dev/null)"; then
    printf '%s\n' "$identity"
    return 0
  fi
  if identity="$(stat -f '%d:%i' -- "$path" 2>/dev/null)"; then
    printf '%s\n' "$identity"
    return 0
  fi
  return 1
}

mihomo_validate_target_host() {
  local host="$1"
  local configured_approved="${MIHOMO_APPROVED_HOST:-}"
  local candidate
  if [[ -n "$configured_approved" && "$configured_approved" != "$host" ]]; then
    printf 'ERROR: MIHOMO_APPROVED_HOST must narrow to the requested host, not change it.\n' >&2
    return 2
  fi
  for candidate in "${MIHOMO_CHECKED_IN_HOSTS[@]}"; do
    [[ "$host" == "$candidate" ]] && return 0
  done
  printf 'ERROR: target host %q is not in the checked-in Mihomo host allowlist.\n' "$host" >&2
  return 2
}

mihomo_prepare_known_hosts() {
  local host="$1"
  local expected_fingerprint="$2"
  local approved_fingerprint scan_file known_hosts_file line hosts key_type key_data fingerprint
  local matched=0
  if [[ "${MIHOMO_EXTERNAL_KNOWN_HOSTS_CONFIG:-0}" == "1" ]]; then
    echo 'ERROR: caller-provided known_hosts ownership/path is not trusted; use the checked-in host identity.' >&2
    return 2
  fi
  approved_fingerprint="$(mihomo_checked_in_fingerprint "$host")" || return 2
  [[ "$expected_fingerprint" == "$approved_fingerprint" ]] || return 2
  # Never delete or reuse a caller-provided path.  Only a file generated by
  # this helper is cleaned up, and it lives in the platform temporary root
  # rather than an operator-controlled TMPDIR.
  mihomo_cleanup_known_hosts || return 2
  known_hosts_file="$(mktemp /tmp/mihomo-known-hosts.XXXXXX)"
  scan_file="${known_hosts_file}.scan"
  chmod 600 "$known_hosts_file"
  if ! ssh-keyscan -T 5 "$host" >"$scan_file" 2>/dev/null; then
    rm -f "$known_hosts_file" "$scan_file"
    return 2
  fi
  # Keep only the exact host/key pair that matched the reviewed fingerprint;
  # accepting the rest of a mixed ssh-keyscan output would let a different key
  # satisfy SSH's host-key check.
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    hosts="$(awk '{print $1}' <<<"$line")"
    key_type="$(awk '{print $2}' <<<"$line")"
    key_data="$(awk '{print $3}' <<<"$line")"
    case ",${hosts}," in
      *,"$host",*) ;;
      *) continue ;;
    esac
    [[ "$key_type" == "ssh-ed25519" && -n "$key_data" ]] || continue
    fingerprint="$(printf '%s %s\n' "$key_type" "$key_data" | ssh-keygen -lf /dev/stdin -E sha256 2>/dev/null | awk '{print $2}')"
    if [[ "$fingerprint" == "$approved_fingerprint" ]]; then
      printf '%s\n' "$line" >> "$known_hosts_file"
      matched=$((matched + 1))
    fi
  done < "$scan_file"
  chmod 600 "$known_hosts_file"
  rm -f "$scan_file"
  if [[ "$matched" != "1" ]]; then
    rm -f "$known_hosts_file"
    return 2
  fi
  MIHOMO_KNOWN_HOSTS_FILE="$known_hosts_file"
  MIHOMO_GENERATED_KNOWN_HOSTS_FILE="$known_hosts_file"
  MIHOMO_GENERATED_KNOWN_HOSTS_IDENTITY="$(mihomo_file_identity "$known_hosts_file")" || {
    rm -f -- "$known_hosts_file"
    MIHOMO_KNOWN_HOSTS_FILE=""
    MIHOMO_GENERATED_KNOWN_HOSTS_FILE=""
    return 2
  }
  [[ -n "$MIHOMO_GENERATED_KNOWN_HOSTS_IDENTITY" ]] || {
    rm -f -- "$known_hosts_file"
    MIHOMO_KNOWN_HOSTS_FILE=""
    MIHOMO_GENERATED_KNOWN_HOSTS_FILE=""
    return 2
  }
  MIHOMO_OWNED_KNOWN_HOSTS_FILE="$known_hosts_file"
  export MIHOMO_OWNED_KNOWN_HOSTS_FILE
  export MIHOMO_KNOWN_HOSTS_FILE
  mihomo_install_known_hosts_cleanup
}

mihomo_cleanup_known_hosts() {
  local path="${MIHOMO_GENERATED_KNOWN_HOSTS_FILE:-}"
  local identity="${MIHOMO_GENERATED_KNOWN_HOSTS_IDENTITY:-}"
  # Only remove a file that this invocation created, at the fixed private
  # temporary location, with the same inode captured immediately after mktemp.
  # A caller-controlled path, symlink, or replaced inode is preserved for
  # manual reconciliation rather than being followed or deleted.
  if [[ -n "$path" ]]; then
    if [[ "$path" != /tmp/mihomo-known-hosts.[A-Za-z0-9]* ||
          -L "$path" || ! -f "$path" || -z "$identity" ||
          "$(mihomo_file_identity "$path" 2>/dev/null || true)" != "$identity" ]]; then
      echo "ERROR: refusing to remove an unverified generated known_hosts path: $path" >&2
    else
      rm -f -- "$path"
      if [[ -e "$path" || -L "$path" ]]; then
        echo "ERROR: generated known_hosts cleanup did not remove $path" >&2
      fi
    fi
  fi
  MIHOMO_GENERATED_KNOWN_HOSTS_FILE=""
  MIHOMO_GENERATED_KNOWN_HOSTS_IDENTITY=""
  MIHOMO_KNOWN_HOSTS_FILE=""
  MIHOMO_OWNED_KNOWN_HOSTS_FILE=""
}

# Do not replace an exit trap owned by the calling script.  The small command
# string is kept only for this process and is evaluated after our temporary
# host-key file has been removed; all callers are repository-owned scripts.
mihomo_install_known_hosts_cleanup() {
  local existing_trap
  existing_trap="$(trap -p EXIT || true)"
  # A second identity check in one process must not recursively chain the
  # helper's own trap.  The current trap already removes the current file.
  if [[ "$existing_trap" == *'MIHOMO_PREVIOUS_EXIT_TRAP'* ]]; then
    return 0
  fi
  if [[ -n "$existing_trap" && "$existing_trap" != "trap -- '' EXIT" ]]; then
    MIHOMO_PREVIOUS_EXIT_TRAP="$existing_trap"
    export MIHOMO_PREVIOUS_EXIT_TRAP
  fi
  trap 'mihomo_cleanup_known_hosts; if [[ -n "${MIHOMO_PREVIOUS_EXIT_TRAP:-}" ]]; then eval "$MIHOMO_PREVIOUS_EXIT_TRAP"; fi' EXIT
}

# Read-only commands still need an independently checked host identity.  The
# caller may select one of the reviewed hosts, but cannot supply a fingerprint
# or known_hosts file that expands trust.
mihomo_prepare_readonly_identity() {
  local host="$1"
  local user="$2"
  local expected_fingerprint
  mihomo_validate_target_host "$host"
  [[ "$user" == "root" ]] || {
    printf 'ERROR: refusing non-root target user %q for read-only operation.\n' "$user" >&2
    return 2
  }
  expected_fingerprint="$(mihomo_checked_in_fingerprint "$host")" || return 2
  command -v ssh-keyscan >/dev/null 2>&1 || {
    echo 'ERROR: ssh-keyscan is required for target identity verification.' >&2
    return 2
  }
  command -v ssh-keygen >/dev/null 2>&1 || {
    echo 'ERROR: ssh-keygen is required for target identity verification.' >&2
    return 2
  }
  mihomo_prepare_known_hosts "$host" "$expected_fingerprint"
}

# Refuse any target not in the checked-in set even for callers that only read.
# Mutating callers additionally require confirmation and a pinned key.
mihomo_require_apply_confirmation() {
  local host="$1"
  local user="$2"
  local confirmed="$3"
  local operation="${4:-host-native mutation}"
  local approved_host="${MIHOMO_APPROVED_HOST:-$host}"
  local expected_fingerprint

  [[ "$confirmed" == "1" ]] || {
    printf 'ERROR: %s requires --confirm; no remote mutation was performed.\n' "$operation" >&2
    return 2
  }
  mihomo_validate_target_host "$host"
  [[ "$host" == "$approved_host" ]] || {
    printf 'ERROR: refusing unapproved target host %q (expected %q).\n' "$host" "$approved_host" >&2
    return 2
  }
  [[ "$user" == "root" ]] || {
    printf 'ERROR: refusing non-root target user %q for %s.\n' "$user" "$operation" >&2
    return 2
  }
  expected_fingerprint="$(mihomo_checked_in_fingerprint "$host")" || {
    printf 'ERROR: no reviewed fingerprint is configured for %q.\n' "$host" >&2
    return 2
  }
  command -v ssh-keyscan >/dev/null 2>&1 || {
    echo 'ERROR: ssh-keyscan is required for target identity verification.' >&2
    return 2
  }
  command -v ssh-keygen >/dev/null 2>&1 || {
    echo 'ERROR: ssh-keygen is required for target identity verification.' >&2
    return 2
  }
  mihomo_prepare_known_hosts "$host" "$expected_fingerprint" || {
    echo "ERROR: could not create a pinned known_hosts file for ${host}." >&2
    return 2
  }
}
